language: java
sudo: false
dist: trusty

matrix:
  include:
    - jdk: oraclejdk8
      addons: {apt: {packages: [oracle-java8-installer]}}
    - jdk: oraclejdk9
      install:
        - cd ..
        - wget http://download.java.net/java/jigsaw/archive/172/binaries/jigsaw-jdk-9-ea+172_linux-x64_bin.tar.gz
        - tar -xzf jigsaw-jdk-9-ea+172_linux-x64_bin.tar.gz
        - export JAVA_HOME=$PWD/jdk-9
        - PATH=$JAVA_HOME/bin:$PATH
        - cd -
        - ./gradlew -version
      env: JDK_JAVA_OPTIONS='--permit-illegal-access'


# Display Gradle version instead of letting Travis execute './gradlew assemble' by default
install:
  - ./gradlew -version

script:
  - ./gradlew build --scan
