language: java
sudo: false
dist: trusty

jdk:
  - oraclejdk8
  - oraclejdk9

# Don't let Travis CI execute './gradlew assemble' by default
install:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version

script:
  - ./gradlew build --scan
